Repository appsignal/appsignal-javascript, pull requests merged in 2022-01, with the labels that each got.

#534 Serialise objects with circular references
  packages/plugin-breadcrumbs-console/.changesets/serialise-circular-references-in-console-arguments.md
  packages/plugin-breadcrumbs-console/src/__tests__/index.test.ts
  packages/plugin-breadcrumbs-console/src/index.ts
Labels: enhancement

#536 Serialise objects with circular references in window errors plugin
  packages/plugin-window-events/.changesets/serialise-circular-references-in-window-errors.md
  packages/plugin-window-events/src/__tests__/index.test.ts
  packages/plugin-window-events/src/index.ts
Labels: enhancement

#541 Update Angular versions in CI
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#538 Fix dependency installation in CI build
  .semaphore/semaphore.yml
  Rakefile
  build_matrix.yml
  package.json
  yarn.lock
Labels: bug

#535 Check if thrown object is error in ErrorBoundary
  packages/core/.changesets/add-internal-utility-to-check-if-object-is-an-error-.md
  packages/core/src/index.ts
  packages/core/src/utils/__tests__/error.test.ts
  packages/core/src/utils/error.ts
  packages/react/.changesets/check-if-thrown-object-is-an-error.md
  packages/react/package.json
  packages/react/src/ErrorBoundary.tsx
  packages/react/src/__tests__/ErrorBoundary.test.tsx
Labels: bug

#542 Bump Node.js to latest 16 release
  .tool-versions
Labels: chore

#543 Check if thrown object is error in ErrorBoundary
  packages/preact/.changesets/.gitkeep
  packages/preact/.changesets/check-if-thrown-object-is-an-error.md
  packages/preact/package.json
  packages/preact/src/ErrorBoundary.tsx
  packages/preact/src/__tests__/ErrorBoundary.test.tsx
Labels: bug

#549 Update package.json metadata
  packages/angular/.changesets/update-package-json-metadata.md
  packages/angular/package.json
  packages/cli/.changesets/update-package-json-metadata.md
  packages/cli/package.json
  packages/core/.changesets/update-package-json-metadata.md
  packages/core/package.json
  packages/ember/.changesets/update-package-json-metadata.md
  packages/ember/package.json
  packages/javascript/.changesets/update-package-json-metadata.md
  packages/javascript/package.json
  packages/plugin-breadcrumbs-console/.changesets/update-package-json-metadata.md
  packages/plugin-breadcrumbs-console/package.json
  packages/plugin-breadcrumbs-network/.changesets/update-package-json-metadata.md
  packages/plugin-breadcrumbs-network/package.json
  packages/plugin-path-decorator/.changesets/update-package-json-metadata.md
  packages/plugin-path-decorator/package.json
  packages/plugin-window-events/.changesets/update-package-json-metadata.md
  packages/plugin-window-events/package.json
  packages/preact/.changesets/update-package-json-metadata.md
  packages/preact/package.json
  packages/react/.changesets/update-package-json-metadata.md
  packages/react/package.json
  packages/stimulus/.changesets/update-package-json-metadata.md
  packages/stimulus/package.json
  packages/types/.changesets/update-package-json-metadata.md
  packages/types/package.json
  packages/vue/.changesets/update-package-json-metadata.md
  packages/vue/package.json
  packages/webpack/.changesets/update-package-json-metadata.md
  packages/webpack/package.json
Labels: chore

#551 Bump axios from 0.21.1 to 0.21.2
  yarn.lock
Labels: chore

#553 Update semver-regex and dependent packages
  yarn.lock
Labels: chore
