Repository appsignal/appsignal-javascript, pull requests merged in 2022-08, with the labels that each got.

#575 Extract message from Error rejection
  packages/core/.changesets/iserror-handle-undefined.md
  packages/core/src/utils/error.ts
  packages/plugin-window-events/.changesets/report-unhandled-rejection-errors.md
  packages/plugin-window-events/package.json
  packages/plugin-window-events/src/__tests__/index.test.ts
  packages/plugin-window-events/src/index.ts
Labels: bug

#577 Bump React peer dependency to allow 18.2.x
  .semaphore/semaphore.yml
  build_matrix.yml
  packages/react/.changesets/bump-peer-dependency-to-allow-react-18-2.md
  packages/react/package.json
Labels: dependencies

#578 Make installation script OpenTelemetry compatible
  packages/cli/src/constants.ts
  packages/cli/src/installers/node/index.ts
Labels: enhancement
